const data = {
  products: [
    {
      name: "Freestyle Shirt",
      slug: "freestyle-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A Popular Shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3,
      numReviews: 7,
      countInStock: 20,
      description: "A Cool Shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 120,
      brand: "Raymond",
      rating: 4.7,
      numReviews: 5,
      countInStock: 0,
      description: "An Expensive Shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 60,
      brand: "Levi",
      rating: 4.2,
      numReviews: 40,
      countInStock: 60,
      description: "A Popular Pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 70,
      brand: "BlueJeans",
      rating: 4.6,
      numReviews: 12,
      countInStock: 22,
      description: "Wicked Pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 44,
      brand: "casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Popular pants",
    },
  ],
};
export default data;
